2018-09-28 11:11:23.667 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:11:23.667 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 11:11:56.121 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:11:56.121 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 10:08:28.339 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:38.353 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:48.363 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:08:58.372 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:08.377 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:09.917 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:18.381 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:28.388 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:38.393 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:48.396 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 10:09:58.407 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:10:49.537 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 11:12:06.077 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:24:47.696 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:24:47.699 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:25:47.920 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:25:47.923 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:31.184 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:31.184 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:31.214 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:31.214 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:31.217 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:31.217 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:31.217 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:31.217 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:31.248 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:31.248 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.645 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.645 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:43.645 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.645 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:43.660 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.660 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:43.660 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.660 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 13:54:43.676 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 13:54:43.676 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
<<<<<<< HEAD
2018-09-28 17:08:09.939 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:09.950 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:08:19.972 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:19.974 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:08:29.978 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:29.978 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
=======
2018-09-28 16:59:34.846 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 16:59:44.868 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 16:59:44.872 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-09-28 16:59:54.889 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 16:59:54.890 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:03:51.371 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:03:51.371 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-09-28 17:04:01.388 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:04:01.390 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-09-28 17:04:11.403 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:04:11.404 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:08:24.828 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:24.828 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:08:34.849 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:34.849 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:08:44.865 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:44.865 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-09-28 17:08:54.880 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:08:54.880 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-09-28 17:09:04.887 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:09:04.887 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:10:51.044 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:10:51.044 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:11:01.070 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:11:01.072 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:11:11.089 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:11:11.089 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-09-28 17:11:21.094 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:11:21.095 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-09-28 17:11:31.101 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:11:31.103 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-09-28 17:17:47.486 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:17:47.493 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-09-28 17:17:57.507 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-09-28 17:17:57.507 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 08:57:29.113 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 08:57:29.119 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 08:57:39.128 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 08:57:39.128 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 08:57:49.154 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 08:57:49.155 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-01 08:57:59.161 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 08:57:59.161 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-01 08:58:09.168 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 08:58:09.168 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
>>>>>>> refs/remotes/origin/develop
2018-10-01 13:39:03.253 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:03.253 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:04.280 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:04.282 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:05.318 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:05.318 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-01 13:39:06.355 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:06.357 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-01 13:39:07.375 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:07.379 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:21.545 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:21.545 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:22.561 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:22.564 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:23.593 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:23.596 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-01 13:39:24.610 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:24.612 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-01 13:39:25.619 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:25.619 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:46.490 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:46.490 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:47.526 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:47.526 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:48.565 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:48.566 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:49.596 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:49.598 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:50.611 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:50.611 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:51.629 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:51.630 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:52.667 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:52.668 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:53.683 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:53.684 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-01 13:39:54.699 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:54.700 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-01 13:39:55.730 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:55.730 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:56.767 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:56.767 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:57.798 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:57.798 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 13:39:59.195 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 13:39:59.195 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-01 15:47:48.836 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 15:47:48.836 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-01 15:47:49.869 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 15:47:49.869 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 15:47:50.904 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 15:47:50.906 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 15:47:51.938 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 15:47:51.938 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-01 15:47:52.955 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-01 15:47:52.955 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 11:23:13.063 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 11:23:13.066 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 11:23:14.073 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 11:23:14.074 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 11:23:15.097 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 11:23:15.097 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-04 11:23:16.103 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 11:23:16.103 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 11:23:17.119 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 11:23:17.119 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:45:34.088 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:34.089 | [main] | ERROR | dao.FacilityDao | DatabaseConnectError
2018-10-04 13:45:35.100 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:35.104 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 13:45:36.111 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:36.111 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:45:37.117 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:37.118 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:45:38.145 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:38.146 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-04 13:45:39.151 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:39.153 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 13:45:40.175 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:40.176 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:45:41.193 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:45:41.194 | [main] | ERROR | dao.OfficeDao | DatabaseConnectError
2018-10-04 13:46:51.025 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:51.025 | [main] | ERROR | dao.FacilityDao | DatabaseConnectError
2018-10-04 13:46:52.043 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:52.044 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 13:46:53.067 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:53.067 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:46:54.086 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:54.086 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:46:55.100 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:55.101 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-04 13:46:56.112 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:56.113 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 13:46:57.135 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:57.136 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 13:46:58.140 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 13:46:58.141 | [main] | ERROR | dao.OfficeDao | DatabaseConnectError
2018-10-04 15:44:38.062 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:38.062 | [main] | ERROR | dao.FacilityDao | DatabaseConnectError
2018-10-04 15:44:39.075 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:39.075 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 15:44:40.090 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:40.091 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 15:44:41.118 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:41.118 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 15:44:42.144 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:42.145 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-04 15:44:43.156 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:43.157 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 15:44:44.163 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:44.164 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 15:44:45.176 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:45.176 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 15:44:46.188 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:46.188 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 15:44:47.202 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 15:44:47.203 | [main] | ERROR | dao.OfficeDao | DatabaseConnectError
2018-10-04 17:09:26.873 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:26.876 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 17:09:27.898 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:27.899 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 17:09:28.905 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:28.906 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-04 17:09:33.547 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:33.549 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-04 17:09:34.569 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:34.570 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 17:09:35.582 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:35.582 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 17:09:36.593 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:36.594 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-04 17:09:37.602 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:37.602 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-04 17:09:38.611 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-04 17:09:38.611 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 10:02:53.098 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:53.102 | [main] | ERROR | dao.FacilityDao | DatabaseConnectError
2018-10-05 10:02:54.108 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:54.109 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 10:02:55.124 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:55.125 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:02:56.135 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:56.136 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:02:57.144 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:57.145 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 10:02:58.152 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:58.152 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:02:59.163 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:02:59.163 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:03:00.170 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:03:00.171 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 10:03:01.183 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:03:01.183 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:03:02.191 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:03:02.191 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:03:03.202 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:03:03.203 | [main] | ERROR | dao.OfficeDao | DatabaseConnectError
2018-10-05 10:04:24.424 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:04:24.428 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 09:33:57.261 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:33:57.262 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 09:33:58.273 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:33:58.274 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 09:33:59.282 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:33:59.283 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 09:34:00.289 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:34:00.289 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 09:34:01.312 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:34:01.312 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 09:34:02.323 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:34:02.324 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 09:34:03.343 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 09:34:03.343 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 10:14:33.844 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:33.847 | [main] | ERROR | dao.FacilityDao | DatabaseConnectError
2018-10-05 10:14:34.874 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:34.875 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 10:14:35.894 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:35.896 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:14:36.936 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:36.936 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:14:37.959 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:37.961 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 10:14:39.001 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:39.002 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:14:40.041 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:40.042 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 10:14:41.063 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:41.064 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:14:42.091 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:42.092 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 10:14:43.127 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 10:14:43.129 | [main] | ERROR | dao.OfficeDao | DatabaseConnectError
2018-10-05 14:02:47.307 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:47.307 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 14:02:48.331 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:48.332 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:02:49.354 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:49.355 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:02:50.364 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:50.365 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:02:51.400 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:51.402 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 14:02:52.411 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:52.411 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 14:02:53.418 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:02:53.418 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 14:13:49.370 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:49.370 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 14:13:50.398 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:50.399 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:13:51.434 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:51.434 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:13:52.452 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:52.452 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 14:13:53.467 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:53.468 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 14:13:54.485 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:54.485 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 14:13:55.522 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 14:13:55.522 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 15:01:27.358 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:27.358 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 15:01:28.381 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:28.386 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:01:29.397 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:29.398 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:01:30.413 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:30.414 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:01:31.438 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:31.440 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 15:01:32.451 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:32.453 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 15:01:33.467 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:01:33.468 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 15:37:58.807 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:37:58.809 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:37:59.833 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:37:59.833 | [main] | ERROR | dao.UserDao | DatabaseConnectError
2018-10-05 15:38:00.849 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:00.849 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:38:01.871 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:01.879 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:38:02.913 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:02.913 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
2018-10-05 15:38:03.968 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:03.968 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 15:38:04.998 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:04.998 | [main] | ERROR | dao.UserDao | DataBaseAcessError
2018-10-05 15:38:06.037 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:06.038 | [main] | ERROR | dao.CategoryDao | DatabaseConnectError
2018-10-05 15:38:07.068 | [main] | ERROR | dao.DBHelper | connectDb() SQLException
2018-10-05 15:38:07.068 | [main] | ERROR | dao.ResourceDao | DatabaseConnectError
